In [1]:
import sys
sys.path.insert(0, "/Users/raghvendraomer/Projects/Sleep_Staging/sleep_staging")

In [6]:
from pre_processing.fitbit_preprocessing import  *

sleep_paths = [
    "/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/sleep-data/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz"
]

heart_paths = [
    "/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/heart-rate/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz",
]

pairs = collect_patient_file_pairs_from_lists(sleep_paths=sleep_paths, heart_paths=heart_paths)

In [4]:
print(pairs)

[('0a85fd46-fada-434c-9f7a-08b81f9ed8e7', PosixPath('/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/sleep-data/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz'), PosixPath('/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/heart-rate/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz'))]

## Sleep data read - add end time based on the value of seconds

In [9]:
df_sleep_data = load_fitbit_sleep_csv("/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/sleep-data/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz")
display(df_sleep_data)

      sleepId            dateTime  level  seconds             endTime
0           1 2018-04-09 23:20:30   wake       30 2018-04-09 23:21:00
1           1 2018-04-09 23:21:00  light      480 2018-04-09 23:29:00
2           1 2018-04-09 23:29:00   deep     2460 2018-04-10 00:10:00
3           1 2018-04-10 00:10:00  light       90 2018-04-10 00:11:30
4           1 2018-04-10 00:11:30    rem     1140 2018-04-10 00:30:30
...       ...                 ...    ...      ...                 ...
1455       84 2018-06-18 04:38:00   wake      210 2018-06-18 04:41:30
1456       84 2018-06-18 04:41:30  light      360 2018-06-18 04:47:30
1457       84 2018-06-18 04:47:30   wake      420 2018-06-18 04:54:30
1458       84 2018-06-18 04:54:30  light      690 2018-06-18 05:06:00
1459       84 2018-06-18 05:06:00   wake      450 2018-06-18 05:13:30

[1460 rows x 5 columns]

## Heart Rate data read

In [12]:
df_heart_data = load_fitbit_heart_rate_csv("/Users/raghvendraomer/Projects/Sleep_Staging/fitbit/heart-rate/0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz",)
display(df_heart_data)

                 timestamp  heart_rate
0      2018-04-09 05:30:30        70.0
1      2018-04-09 05:30:35        86.0
2      2018-04-09 05:30:40        93.0
3      2018-04-09 05:30:45        99.0
4      2018-04-09 05:30:50       103.0
...                    ...         ...
666933 2018-06-18 18:45:15        70.0
666934 2018-06-18 19:13:02        70.0
666935 2018-06-18 21:00:51        70.0
666936 2018-06-18 21:26:16        70.0
666937 2018-06-18 22:05:24        70.0

[666938 rows x 2 columns]

In [20]:
df_sleep_data_2 = sleep_intervals_to_epoch_labels(
    sleep_df = df_sleep_data,
    epoch_sec = 30,
    label_strategy = "mode",
)
display(df_sleep_data_2)

       sleepId           timestamp  level
0            1 2018-04-09 23:20:30   wake
1            1 2018-04-09 23:21:00  light
2            1 2018-04-09 23:21:30  light
3            1 2018-04-09 23:22:00  light
4            1 2018-04-09 23:22:30  light
...        ...                 ...    ...
48370       84 2018-06-18 05:11:00   wake
48371       84 2018-06-18 05:11:30   wake
48372       84 2018-06-18 05:12:00   wake
48373       84 2018-06-18 05:12:30   wake
48374       84 2018-06-18 05:13:00   wake

[48375 rows x 3 columns]

In [19]:
df_heart_2 = resample_heart_rate(
    heart_df = df_heart_data,
    sampling_hz = 1.0,
    interpolation = "linear",
    normalize_per_night = False,
    segments = None,
)
display(df_heart_2)

                  timestamp  heart_rate
0       2018-04-09 05:30:30        70.0
1       2018-04-09 05:30:31        73.2
2       2018-04-09 05:30:32        76.4
3       2018-04-09 05:30:33        79.6
4       2018-04-09 05:30:34        82.8
...                     ...         ...
6107690 2018-06-18 22:05:20        70.0
6107691 2018-06-18 22:05:21        70.0
6107692 2018-06-18 22:05:22        70.0
6107693 2018-06-18 22:05:23        70.0
6107694 2018-06-18 22:05:24        70.0

[6107695 rows x 2 columns]