In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
!ls -la drive/MyDrive/fitbit/heart-rate/
!ls -la drive/MyDrive/fitbit/sleep-data/

total 387986
-rw------- 1 root root 1885537 Aug  5  2025 02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz
-rw------- 1 root root 2533329 Aug  5  2025 0271c478-a56a-4c09-ab91-9743184dd71b.csv.gz
-rw------- 1 root root 2559953 Aug  5  2025 02b7a595-6508-46bd-8239-6deb433d6290.csv.gz
-rw------- 1 root root 1736853 Aug  5  2025 05dedb61-63bc-44e3-8e28-a5d32d91f7e9.csv.gz
-rw------- 1 root root 2810496 Aug  5  2025 06b33ec4-706d-462f-a681-05491be38eb3.csv.gz
drwx------ 2 root root    4096 Apr 20 23:35 0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv
-rw------- 1 root root 2365891 Aug  5  2025 0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz
drwx------ 2 root root    4096 Apr 20 23:35 0adb7679-9d26-46e7-a134-11da293910f3.csv
-rw------- 1 root root 2058512 Aug  5  2025 0adb7679-9d26-46e7-a134-11da293910f3.csv.gz
-rw------- 1 root root 1777938 Aug  5  2025 0b45e9c1-eba5-46d3-b0a4-cdb5aa4dc736.csv.gz
-rw------- 1 root root 1106938 Aug  5  2025 0bf54591-e0ac-47ba-9b43-31ff54dfcee8.csv.gz
-rw------- 1 root root 1762721 Aug  5  2025 0e33f78a-7064-44ff-a8a4-711f99113d39.csv.gz
-rw------- 1 root root 4259583 Aug  5  2025 0e615090-ca26-4635-9590-f6e6cde1094f.csv.gz
-rw------- 1 root root 2370567 Aug  5  2025 0ec84778-1a98-4cd7-aa11-05997ddadd52.csv.gz
-rw------- 1 root root 1645989 Aug  5  2025 113be918-e2d0-443c-830d-fd0964042b9d.csv.gz
-rw------- 1 root root 2133962 Aug  5  2025 11ee71b5-e66b-4da3-8458-fc4db17d875a.csv.gz
-rw------- 1 root root 2651967 Aug  5  2025 132c620a-fa7c-4f95-8dbf-9edc6f973336.csv.gz
-rw------- 1 root root 2195238 Aug  5  2025 13c66354-c2ce-4471-974d-0fd776a8a1bb.csv.gz
-rw------- 1 root root 2232569 Aug  5  2025 14121de2-f38e-4906-9fbe-b613549623fd.csv.gz
-rw------- 1 root root 1436765 Aug  5  2025 14eb688e-385b-4d6c-8cc1-0d51d89f4b2a.csv.gz
drwx------ 2 root root    4096 Apr 20 23:35 1586a0ff-0e95-4b1d-a2bd-97863a02811b.csv
-rw------- 1 root root 1331837 Aug  5  2025 1586a0ff-0e95-4b1d-a2bd-97863a02811b.csv.gz
-rw------- 1 root root 1791816 Aug  5  2025 16213162-1d73-4155-8103-fa668f1579b6.csv.gz
-rw------- 1 root root  743628 Aug  5  2025 16812063-e5df-4657-b86c-5b55a0c9ffe6.csv.gz
-rw------- 1 root root 1360018 Aug  5  2025 18159216-429a-4921-ab5f-7e751b5fdaad.csv.gz
-rw------- 1 root root 1764121 Aug  5  2025 19097e81-ae0b-4ef1-b5aa-84350c2feeb9.csv.gz
-rw------- 1 root root  378241 Aug  5  2025 1b1bcdb5-00eb-4a8c-8c05-a70d678ca0f8.csv.gz
-rw------- 1 root root 1282930 Aug  5  2025 1d356286-db62-4eaa-a4ef-3ba004e06843.csv.gz
-rw------- 1 root root 2464934 Aug  5  2025 20aa0d7b-c28d-43f1-a79c-c77a671b9d05.csv.gz
-rw------- 1 root root 1008796 Aug  5  2025 218a0ad7-4922-4c84-a41f-1b7abbfb72f7.csv.gz
-rw------- 1 root root 2108683 Aug  5  2025 21e4864a-7534-467b-9b55-2ec244a98037.csv.gz
-rw------- 1 root root 2186179 Aug  5  2025 235be35e-4e50-4996-80d7-ce701d2dca4b.csv.gz
-rw------- 1 root root 2688011 Aug  5  2025 23a4808f-4429-41d7-adcf-c96742871613.csv.gz
-rw------- 1 root root 1241290 Aug  5  2025 24166136-6ee3-4521-abaf-972fbe83d15d.csv.gz
-rw------- 1 root root 2555061 Aug  5  2025 24e975f6-80e9-4489-afed-d7f93e499aeb.csv.gz
-rw------- 1 root root 2521590 Aug  5  2025 29d662a9-f454-4261-8d58-f208c07cfd20.csv.gz
-rw------- 1 root root  739022 Aug  5  2025 29e729f1-575c-4627-bf5a-e7bc28fdda26.csv.gz
-rw------- 1 root root 2615413 Aug  5  2025 2a3ed8d1-f62c-42b5-8efe-44f6a61cd6b4.csv.gz
-rw------- 1 root root 2519793 Aug  5  2025 2a8f6d94-88d4-4d72-b304-782563903dca.csv.gz
-rw------- 1 root root 2619508 Aug  5  2025 2aae82c5-03f9-42dd-974d-88230a9b75f7.csv.gz
-rw------- 1 root root 2404076 Aug  5  2025 2b0a7c5a-98f9-4512-a297-3ae27e805b71.csv.gz
-rw------- 1 root root  942547 Aug  5  2025 2d05ec74-7279-4b26-b3ec-d3a2e414ba43.csv.gz
-rw------- 1 root root 1505638 Aug  5  2025 2db06051-769a-4daa-8e8e-3d3e6f9c5a17.csv.gz
-rw------- 1 root root 2640372 Aug  5  2025 2ec7547d-bd0a-4fbf-92a8-3a4e747a53f9.csv.gz
-rw------- 1 root root 2617820 Aug  5  2025 300a4242-7c38-4d7a-8911-2914ef452ab3.csv.gz
-rw------- 1 root root 2463417 Aug  5  2025 30141090-2743-49fb-94e0-25bfa783bcfd.csv.gz
-rw------- 1 root root  806362 Aug  5  2025 32de9693-b5b6-4292-addd-2acbce93d8db.csv.gz
-rw------- 1 root root 2842482 Aug  5  2025 333a79d3-374a-43e5-8bfe-0f14e65b3db7.csv.gz
-rw------- 1 root root 1086281 Aug  5  2025 34c508d4-cbc4-46a4-8a71-890fb3d36724.csv.gz
-rw------- 1 root root 2888246 Aug  5  2025 36d8aa27-272b-460f-8f2c-13d22f7150a5.csv.gz
-rw------- 1 root root 1407433 Aug  5  2025 3a3fbad0-dca2-4c2b-82fb-0f6574b0bc0c.csv.gz
-rw------- 1 root root 2791238 Aug  5  2025 3a442eb1-e680-40ce-afcb-e718c4f1eb09.csv.gz
-rw------- 1 root root 1178122 Aug  5  2025 3a62899e-082a-4638-ab8b-b49f1ce12a20.csv.gz
-rw------- 1 root root  580682 Aug  5  2025 3bdb1a29-023b-4fb5-8f49-6d285446179d.csv.gz
-rw------- 1 root root 1517531 Aug  5  2025 3cc3da4a-9b07-4215-ad8c-7ef222571856.csv.gz
-rw------- 1 root root 1035270 Aug  5  2025 3cd6a70c-1102-4097-b846-d42e975e901c.csv.gz
-rw------- 1 root root 2320980 Aug  5  2025 3cd9d6ee-2d46-46f3-928a-109147d08549.csv.gz
-rw------- 1 root root  348273 Aug  5  2025 41f2fcc5-e1a6-42d0-9b51-68682d173e6f.csv.gz
-rw------- 1 root root 2191791 Aug  5  2025 425f3be7-a142-4256-af48-25ecedd8c425.csv.gz
-rw------- 1 root root  628417 Aug  5  2025 43d50656-b760-4700-8ff1-da45f17bba09.csv.gz
-rw------- 1 root root 1075503 Aug  5  2025 4720363c-e587-4dcf-bc00-1b3bb42e7dc8.csv.gz
-rw------- 1 root root 2497069 Aug  5  2025 481aca07-ac33-4f38-98b7-3405dc3d60dc.csv.gz
-rw------- 1 root root 1850866 Aug  5  2025 49a44e13-111a-4f8d-b4ea-5d3476cb83a3.csv.gz
-rw------- 1 root root 1760236 Aug  5  2025 4b5a5d57-0ad9-49fc-913f-d9e33b90b159.csv.gz
-rw------- 1 root root 2085510 Aug  5  2025 4b8d9e5c-1e51-4a1d-81c9-b3911f623c08.csv.gz
-rw------- 1 root root  946102 Aug  5  2025 4e471779-ecbc-4b5a-b6b0-fcbfc9479faa.csv.gz
-rw------- 1 root root 2339335 Aug  5  2025 4e541136-0db1-4749-b4c1-8dc03df3d4a5.csv.gz
-rw------- 1 root root 1758014 Aug  5  2025 4ea2ae1d-8d6b-4c7f-ac60-27fd6e5b67b0.csv.gz
-rw------- 1 root root 2090159 Aug  5  2025 4ed3225f-868e-43c6-9e57-0329d9ff9e9d.csv.gz
-rw------- 1 root root 2026832 Aug  5  2025 5072f60b-88da-4fd2-8339-f2c45496ffa4.csv.gz
-rw------- 1 root root 2773791 Aug  5  2025 51adda7d-b627-48e0-98be-72386fc84661.csv.gz
-rw------- 1 root root 2039738 Aug  5  2025 5375b0e9-db92-4189-801a-1e9dbe1d9f61.csv.gz
-rw------- 1 root root 2742715 Aug  5  2025 5bb7f10e-ea7d-4af3-adae-c0d92e8a700d.csv.gz
-rw------- 1 root root 2527056 Aug  5  2025 5c7c51c5-8bd6-4997-92c1-ce4c5eda45e6.csv.gz
-rw------- 1 root root 1649820 Aug  5  2025 5dc874cc-0b53-449b-bfa9-57fb665f388b.csv.gz
-rw------- 1 root root  146337 Aug  5  2025 62e88542-8d2e-4148-bd5f-2a3b47cdac44.csv.gz
-rw------- 1 root root 2751920 Aug  5  2025 640d48a2-510a-49e6-bb3e-5bbd92222489.csv.gz
-rw------- 1 root root 2508150 Aug  5  2025 658adbe4-781c-45f9-92a7-14912fcd0701.csv.gz
-rw------- 1 root root 1707755 Aug  5  2025 663de5e8-dfc8-42ad-8410-c196f6345bec.csv.gz
-rw------- 1 root root 2731898 Aug  5  2025 665117c8-5dde-4655-a286-cd8ef2603d59.csv.gz
-rw------- 1 root root 1888900 Aug  5  2025 674e9815-7dd1-47f9-9916-c6e53d7e1a36.csv.gz
-rw------- 1 root root 2369400 Aug  5  2025 67d47ef6-5f27-43cd-912a-a40f27a43660.csv.gz
-rw------- 1 root root 2455400 Aug  5  2025 6812b3d0-5a2f-4d11-960a-23fc5c4e8c7b.csv.gz
-rw------- 1 root root 1556879 Aug  5  2025 687c2d53-012d-4082-a5f0-edade97481a5.csv.gz
-rw------- 1 root root  647555 Aug  5  2025 69c89ffd-abcc-445b-9168-d2c42ab4e7ee.csv.gz
-rw------- 1 root root 2800947 Aug  5  2025 6a0fa84c-b18c-417c-b1f5-6a1a2528f7ee.csv.gz
-rw------- 1 root root 2648747 Aug  5  2025 6ceb4ef3-6578-45cc-bc02-fa97614313e1.csv.gz
-rw------- 1 root root 1602799 Aug  5  2025 6d10bf7a-a17c-4c87-9251-ae75e8f06f36.csv.gz
-rw------- 1 root root 2687465 Aug  5  2025 6f532efb-8e13-46ca-997d-2d934b5e5a37.csv.gz
-rw------- 1 root root 2871583 Aug  5  2025 6fb467a6-a780-4753-9fda-269594a5b928.csv.gz
-rw------- 1 root root 1125296 Aug  5  2025 7145fd25-94b9-49d3-b570-cf77f0221213.csv.gz
-rw------- 1 root root 1209639 Aug  5  2025 716e0022-85e1-45f0-853a-ca8f003da51a.csv.gz
-rw------- 1 root root 1689958 Aug  5  2025 71931795-5de7-4863-ae0c-3fb5edb5f9e0.csv.gz
-rw------- 1 root root 1903853 Aug  5  2025 757d34ef-7f1b-41f5-b072-ea4a4f336b80.csv.gz
-rw------- 1 root root 2092120 Aug  5  2025 75c633d4-6ade-471e-983a-aadc07d9383c.csv.gz
-rw------- 1 root root 2230301 Aug  5  2025 7607c6de-7244-4ba1-ab7c-5c4c4d7151ad.csv.gz
-rw------- 1 root root 2692236 Aug  5  2025 77dfe9b8-5f40-49a6-ba09-706198bb8a48.csv.gz
-rw------- 1 root root  997775 Aug  5  2025 787b23f7-f912-43c4-8caf-7a16c57e0256.csv.gz
-rw------- 1 root root 1805802 Aug  5  2025 7b0d87b0-c099-44eb-9815-67d51d73db9a.csv.gz
-rw------- 1 root root 1942288 Aug  5  2025 7b497dbd-18ec-4d3c-88dd-e9f1d67fb493.csv.gz
-rw------- 1 root root 1783130 Aug  5  2025 7bb5eee8-70d6-4b16-990a-a62cf827170a.csv.gz
-rw------- 1 root root 2826048 Aug  5  2025 7c34bf1b-3b8b-45cd-ae97-26f2eafe97dd.csv.gz
-rw------- 1 root root 2604764 Aug  5  2025 7c885f26-7923-41a3-847e-c971eafee8d4.csv.gz
-rw------- 1 root root 1566427 Aug  5  2025 7e6a98f1-73c3-4023-9bbd-acf2b70d04b5.csv.gz
-rw------- 1 root root 2876772 Aug  5  2025 7e883e52-65af-4edb-9d55-a72ba5f03287.csv.gz
-rw------- 1 root root   90197 Aug  5  2025 803be457-cee4-4f3f-9540-ff574c57c697.csv.gz
-rw------- 1 root root 2238258 Aug  5  2025 8307ff6e-f582-49b0-81cc-39fe9966d097.csv.gz
-rw------- 1 root root 2437141 Aug  5  2025 8323bb7d-6b8d-4dea-82d6-08944e6da3a9.csv.gz
-rw------- 1 root root 1049900 Aug  5  2025 85c88df0-b503-4329-a29f-353199f7fe5b.csv.gz
-rw------- 1 root root 2237840 Aug  5  2025 883aca61-af06-4c14-ba58-8d2e4b75bfda.csv.gz
-rw------- 1 root root 2262645 Aug  5  2025 885170be-d945-427d-bd3a-b0524ddc3105.csv.gz
-rw------- 1 root root 1522061 Aug  5  2025 89ff7373-ee85-4764-a4dd-90138af9af85.csv.gz
-rw------- 1 root root 2273678 Aug  5  2025 8a01ec4c-6222-4efd-9beb-0adb12e00a2b.csv.gz
-rw------- 1 root root 1631002 Aug  5  2025 8a2a2baf-826f-445d-a7fe-3a9b7f5d2334.csv.gz
-rw------- 1 root root 2532904 Aug  5  2025 8b13d979-315f-4357-8f0e-7c12df0a6ca8.csv.gz
-rw------- 1 root root 1098273 Aug  5  2025 8c09fe40-2c9e-49a1-afc9-a37138658d3b.csv.gz
-rw------- 1 root root 2242338 Aug  5  2025 8c0d11a7-1838-4db4-9319-5d171522655d.csv.gz
-rw------- 1 root root  919999 Aug  5  2025 8f1c82eb-5e71-4187-a0a3-f2b58d8d99bd.csv.gz
-rw------- 1 root root 1364459 Aug  5  2025 900bd2b1-a14f-4775-8f78-07ba77caf23b.csv.gz
-rw------- 1 root root   54395 Aug  5  2025 91297102-4775-4ea1-a10d-4530e3c2f0af.csv.gz
-rw------- 1 root root 1033283 Aug  5  2025 9276d1e3-6954-460f-bd75-7f99fa01345c.csv.gz
-rw------- 1 root root 1927973 Aug  5  2025 9519432e-bf05-4f6c-80d7-f61e930f14ba.csv.gz
-rw------- 1 root root 2132194 Aug  5  2025 9548d1c4-bd4a-4841-9146-c0678135069d.csv.gz
-rw------- 1 root root 2319195 Aug  5  2025 95f9f3a8-128c-4382-aa4b-6ea319b497ae.csv.gz
-rw------- 1 root root 1400001 Aug  5  2025 967b5d47-3ff4-4364-b2e8-b2243c490d7d.csv.gz
-rw------- 1 root root 2560152 Aug  5  2025 96a272fc-166f-4fe4-8aeb-3874264f3b54.csv.gz
-rw------- 1 root root 2161101 Aug  5  2025 997c6352-6724-4985-b48c-9c3f08437964.csv.gz
-rw------- 1 root root 1941484 Aug  5  2025 9b4822a9-8506-4026-8f8f-803410f95a52.csv.gz
-rw------- 1 root root 2679036 Aug  5  2025 9c4b0b2a-92e1-4aeb-be90-98f65c1d4217.csv.gz
-rw------- 1 root root 2035571 Aug  5  2025 9f956795-08fb-4518-98c5-481696722acd.csv.gz
-rw------- 1 root root 2206283 Aug  5  2025 a0746eca-480e-41ac-bc92-d31568b2bdaf.csv.gz
-rw------- 1 root root 2357560 Aug  5  2025 a09f7021-3875-48f3-ab98-b7ae623fb91a.csv.gz
-rw------- 1 root root 1394065 Aug  5  2025 a0fce948-41d2-4070-bad2-ab8d17bf97d8.csv.gz
-rw------- 1 root root 2350623 Aug  5  2025 a1395d16-e27d-4ff3-80ba-2bb22049c19d.csv.gz
-rw------- 1 root root 1628108 Aug  5  2025 a1623554-43d6-4038-b28a-bd74a96b9c97.csv.gz
-rw------- 1 root root 1971731 Aug  5  2025 a255dc52-384b-4d4c-a612-33a02fa6c409.csv.gz
-rw------- 1 root root 1176290 Aug  5  2025 a2664330-dcfa-4d43-a788-8904343b6a00.csv.gz
-rw------- 1 root root 2208847 Aug  5  2025 a4b481fd-66b2-4b01-a3a7-906af1f81663.csv.gz
-rw------- 1 root root 2640233 Aug  5  2025 a575b34b-0787-4762-a06a-5604de6d005b.csv.gz
-rw------- 1 root root 1788043 Aug  5  2025 a60ebd9e-fa87-4722-8960-b26290ddae1a.csv.gz
-rw------- 1 root root 2571953 Aug  5  2025 a70d820b-e850-44c4-ab12-1b40e0f7ae39.csv.gz
-rw------- 1 root root 1984925 Aug  5  2025 a7633bbc-3145-4bba-b86b-cef5e4ae3273.csv.gz
-rw------- 1 root root 2548487 Aug  5  2025 a7db3311-aa07-4580-b552-73c18657c803.csv.gz
-rw------- 1 root root 1412585 Aug  5  2025 a81eedd1-fb39-4763-bf76-a0472f78ce9f.csv.gz
-rw------- 1 root root  857814 Aug  5  2025 a8800ef0-619c-4a3c-af5b-df1d2a3a6f71.csv.gz
-rw------- 1 root root 2109505 Aug  5  2025 a9dfbe4d-4076-48c7-a72b-342fe4c12514.csv.gz
-rw------- 1 root root 2580469 Aug  5  2025 aa8d1b7a-14c6-4490-a57b-d3893ac28b03.csv.gz
-rw------- 1 root root 1109386 Aug  5  2025 aae509f5-ab41-43a0-85c2-5dfad0ed520a.csv.gz
-rw------- 1 root root 2149372 Aug  5  2025 ab23fe51-7249-4c81-bec3-451b6ab1d140.csv.gz
-rw------- 1 root root  447940 Aug  5  2025 adc70680-fedc-481e-be34-32c6630ab3cd.csv.gz
-rw------- 1 root root 1621889 Aug  5  2025 aea11c01-40d9-479e-aa27-0b8bf464de52.csv.gz
-rw------- 1 root root 2280122 Aug  5  2025 aef21a29-6b16-4d49-9a07-96c12fcd5698.csv.gz
-rw------- 1 root root 2240112 Aug  5  2025 b24987c0-4530-45b4-8dc1-c42c4e0cd7ad.csv.gz
-rw------- 1 root root 1337523 Aug  5  2025 b318de0d-0b0a-4ba8-a7be-9fcf7b9d8c67.csv.gz
-rw------- 1 root root 2261278 Aug  5  2025 b31b6e69-0384-4d5d-8eac-5f512862690b.csv.gz
-rw------- 1 root root 1120423 Aug  5  2025 ba240e43-900d-4477-8718-b9487ed24d7d.csv.gz
-rw------- 1 root root 1523691 Aug  5  2025 bdb64352-b982-4aab-8d98-3c56c5a6441f.csv.gz
-rw------- 1 root root  660274 Aug  5  2025 be0e8360-24c6-4d74-ab72-aadf8d8acc82.csv.gz
-rw------- 1 root root 2461569 Aug  5  2025 be2b627b-a267-4bd6-a36b-c9dcc2065f0c.csv.gz
-rw------- 1 root root 2243494 Aug  5  2025 c131a94c-b958-454b-bbd0-2f0de3b7ae5a.csv.gz
-rw------- 1 root root 1392540 Aug  5  2025 c29d3319-8920-46b9-9b3a-11c36630c87d.csv.gz
-rw------- 1 root root 1846594 Aug  5  2025 c35d219d-59d9-4197-b981-ea0aa6506e79.csv.gz
-rw------- 1 root root 2647436 Aug  5  2025 c7492565-48cd-4b52-af25-3aee61a391ad.csv.gz
-rw------- 1 root root 2000930 Aug  5  2025 c7acafcf-f5dd-411e-b90c-988279852fb8.csv.gz
-rw------- 1 root root 2775292 Aug  5  2025 c7c4392b-02ee-40f4-a22f-ab2386c6ccf5.csv.gz
-rw------- 1 root root 2019779 Aug  5  2025 c9fd26bd-1c5d-4d80-a298-8304267cfb4c.csv.gz
-rw------- 1 root root 2340675 Aug  5  2025 ca202c8f-5071-4358-8851-3c580ec157b1.csv.gz
-rw------- 1 root root 2146935 Aug  5  2025 cc25830a-254a-487f-acec-c0afb3962679.csv.gz
-rw------- 1 root root 1768381 Aug  5  2025 cc6aaebf-0430-4bf2-b3b7-f416daf008c7.csv.gz
-rw------- 1 root root 1424443 Aug  5  2025 cdcb783e-c9fd-4eab-9d6c-2a53e4082a1f.csv.gz
-rw------- 1 root root 2349054 Aug  5  2025 cffbcf00-a329-4d57-a622-6e85ca913704.csv.gz
-rw------- 1 root root 2380729 Aug  5  2025 d046a3ef-1402-4530-855c-481798c41ccd.csv.gz
-rw------- 1 root root 1356549 Aug  5  2025 d127b095-98d4-4149-bdfc-c9f9739e6f18.csv.gz
-rw------- 1 root root 1278535 Aug  5  2025 d28b2c23-1da4-4b64-be94-df4aa6121559.csv.gz
-rw------- 1 root root 2473417 Aug  5  2025 d62a5591-4c0c-4c95-9187-faa64b95f9fc.csv.gz
-rw------- 1 root root 2412189 Aug  5  2025 dafdc3d9-e474-4556-8958-204f68ad5ebc.csv.gz
-rw------- 1 root root 1268588 Aug  5  2025 db082772-c8cc-4df4-a647-6a80ee2db9ce.csv.gz
-rw------- 1 root root  499063 Aug  5  2025 db2bffd9-c5b5-4fed-9d55-09a087ce0e6e.csv.gz
-rw------- 1 root root  853760 Aug  5  2025 dc65ee54-ad64-4cce-8d0a-878033ff02d7.csv.gz
-rw------- 1 root root 2149606 Aug  5  2025 dcc3e9ff-9c05-4e17-9798-fd5114be77a9.csv.gz
-rw------- 1 root root 2511547 Aug  5  2025 deb03e25-16f1-403a-8152-891f50b50ae4.csv.gz
-rw------- 1 root root 2007035 Aug  5  2025 df3a6b7a-7e27-4003-beea-2cb5cf08da83.csv.gz
-rw------- 1 root root 2546211 Aug  5  2025 e027002a-cf96-4132-a4ac-2003e945258d.csv.gz
-rw------- 1 root root 2418942 Aug  5  2025 e05bec91-93e2-4b23-9d4f-ae79dade8451.csv.gz
-rw------- 1 root root 1471741 Aug  5  2025 e31e0dfd-b00c-43e4-a1ea-f5110bf01c1c.csv.gz
-rw------- 1 root root  152169 Aug  5  2025 e3e5e4aa-5950-4f1f-915c-c67598965b03.csv.gz
-rw------- 1 root root 2662317 Aug  5  2025 e5be76f8-6461-481b-834e-b44f8f880273.csv.gz
-rw------- 1 root root 3033301 Aug  5  2025 e6081755-d7f3-4c26-ab40-0709b8ad41ef.csv.gz
-rw------- 1 root root 2328177 Aug  5  2025 e8606fff-0ac6-4832-bb79-323b89ebcf2e.csv.gz
-rw------- 1 root root 3188629 Aug  5  2025 e89b1ea7-a2ea-4f2f-ae5a-9a9d29af8639.csv.gz
-rw------- 1 root root 2130714 Aug  5  2025 e8c7086f-007a-41c5-a7dc-af81612ab14d.csv.gz
-rw------- 1 root root 1971532 Aug  5  2025 eb4e1be4-29de-4120-9727-0ce8041da479.csv.gz
-rw------- 1 root root  698869 Aug  5  2025 edec36ec-64c2-4cf8-af5c-99f4c8972d30.csv.gz
-rw------- 1 root root 1581471 Aug  5  2025 edf9689d-5d97-4fe9-b3e7-64c96d9a169c.csv.gz
-rw------- 1 root root  917119 Aug  5  2025 efc0dabd-1c17-4a63-89ca-21f65250e43f.csv.gz
-rw------- 1 root root 2483771 Aug  5  2025 f0bf3cda-f934-459f-a731-dd7eda243ae7.csv.gz
-rw------- 1 root root 1361610 Aug  5  2025 f2e8ab49-ce1b-45f4-9632-cf596f1196bb.csv.gz
-rw------- 1 root root  353891 Aug  5  2025 f30085f9-fdb0-49fb-b242-2ad8286b242c.csv.gz
-rw------- 1 root root 2146073 Aug  5  2025 f3a1263e-f498-4942-829a-f40d186caa08.csv.gz
-rw------- 1 root root 2604583 Aug  5  2025 f596b3ca-7b25-4632-b986-7b44448d3f2f.csv.gz
-rw------- 1 root root 2336009 Aug  5  2025 f5c8d104-4839-4aca-b2f5-8c2fc4b98af9.csv.gz
-rw------- 1 root root 2461039 Aug  5  2025 f610ffea-f6cb-4182-bbe7-19ff8fbe66ee.csv.gz
-rw------- 1 root root 1931239 Aug  5  2025 f732e878-e538-49b8-97d3-49ca29e9a3f8.csv.gz
-rw------- 1 root root 2539326 Aug  5  2025 f9264a9d-99d8-4937-8bda-eb620c0c1ed7.csv.gz
-rw------- 1 root root 2224080 Aug  5  2025 f983485d-f954-4693-9c2c-981710c06dd0.csv.gz
-rw------- 1 root root 2107921 Aug  5  2025 fabef151-53c8-4a46-9897-0180868a53f5.csv.gz
-rw------- 1 root root 2530130 Aug  5  2025 fae38580-1e2d-4491-9de5-7b75703ba4ce.csv.gz
-rw------- 1 root root  421695 Aug  5  2025 fb3a4dd7-3cb5-438e-a75d-244d1aec4790.csv.gz
-rw------- 1 root root 2447381 Aug  5  2025 fcb14a4c-1ffa-4315-872a-a38833459885.csv.gz
-rw------- 1 root root 1791681 Aug  5  2025 fd79ab30-1199-4619-adbd-577d715d86ce.csv.gz
-rw------- 1 root root 2573656 Aug  5  2025 fdbd8c07-720c-4ae5-a3d8-aad56b54688c.csv.gz
-rw------- 1 root root     634 Aug  5  2025 README.md

total 1278
-rw------- 1 root root  6136 Aug  5  2025 02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz
-rw------- 1 root root 11022 Aug  5  2025 0271c478-a56a-4c09-ab91-9743184dd71b.csv.gz
-rw------- 1 root root  9261 Aug  5  2025 02b7a595-6508-46bd-8239-6deb433d6290.csv.gz
-rw------- 1 root root  4438 Aug  5  2025 05dedb61-63bc-44e3-8e28-a5d32d91f7e9.csv.gz
-rw------- 1 root root  9154 Aug  5  2025 06b33ec4-706d-462f-a681-05491be38eb3.csv.gz
drwx------ 2 root root  4096 Apr 20 23:35 0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv
-rw------- 1 root root  8282 Aug  5  2025 0a85fd46-fada-434c-9f7a-08b81f9ed8e7.csv.gz
drwx------ 2 root root  4096 Apr 20 23:35 0adb7679-9d26-46e7-a134-11da293910f3.csv
-rw------- 1 root root  9949 Aug  5  2025 0adb7679-9d26-46e7-a134-11da293910f3.csv.gz
-rw------- 1 root root  3804 Aug  5  2025 0b45e9c1-eba5-46d3-b0a4-cdb5aa4dc736.csv.gz
-rw------- 1 root root   391 Aug  5  2025 0bf54591-e0ac-47ba-9b43-31ff54dfcee8.csv.gz
-rw------- 1 root root  4840 Aug  5  2025 0e33f78a-7064-44ff-a8a4-711f99113d39.csv.gz
drwx------ 2 root root  4096 Apr 20 23:35 0e615090-ca26-4635-9590-f6e6cde1094f.csv
-rw------- 1 root root  9230 Aug  5  2025 0e615090-ca26-4635-9590-f6e6cde1094f.csv.gz
-rw------- 1 root root  8684 Aug  5  2025 0ec84778-1a98-4cd7-aa11-05997ddadd52.csv.gz
-rw------- 1 root root   579 Aug  5  2025 113be918-e2d0-443c-830d-fd0964042b9d.csv.gz
-rw------- 1 root root  6700 Aug  5  2025 11ee71b5-e66b-4da3-8458-fc4db17d875a.csv.gz
-rw------- 1 root root 10412 Aug  5  2025 132c620a-fa7c-4f95-8dbf-9edc6f973336.csv.gz
-rw------- 1 root root  6611 Aug  5  2025 13c66354-c2ce-4471-974d-0fd776a8a1bb.csv.gz
-rw------- 1 root root  6451 Aug  5  2025 14121de2-f38e-4906-9fbe-b613549623fd.csv.gz
-rw------- 1 root root   897 Aug  5  2025 14eb688e-385b-4d6c-8cc1-0d51d89f4b2a.csv.gz
drwx------ 2 root root  4096 Apr 20 23:35 1586a0ff-0e95-4b1d-a2bd-97863a02811b.csv
-rw------- 1 root root  1955 Aug  5  2025 1586a0ff-0e95-4b1d-a2bd-97863a02811b.csv.gz
-rw------- 1 root root  6677 Aug  5  2025 16213162-1d73-4155-8103-fa668f1579b6.csv.gz
-rw------- 1 root root   304 Aug  5  2025 16812063-e5df-4657-b86c-5b55a0c9ffe6.csv.gz
-rw------- 1 root root  3532 Aug  5  2025 18159216-429a-4921-ab5f-7e751b5fdaad.csv.gz
-rw------- 1 root root   694 Aug  5  2025 19097e81-ae0b-4ef1-b5aa-84350c2feeb9.csv.gz
-rw------- 1 root root   182 Aug  5  2025 1b1bcdb5-00eb-4a8c-8c05-a70d678ca0f8.csv.gz
-rw------- 1 root root  1823 Aug  5  2025 1d356286-db62-4eaa-a4ef-3ba004e06843.csv.gz
-rw------- 1 root root  9257 Aug  5  2025 20aa0d7b-c28d-43f1-a79c-c77a671b9d05.csv.gz
-rw------- 1 root root  2323 Aug  5  2025 218a0ad7-4922-4c84-a41f-1b7abbfb72f7.csv.gz
-rw------- 1 root root  9256 Aug  5  2025 21e4864a-7534-467b-9b55-2ec244a98037.csv.gz
-rw------- 1 root root  7063 Aug  5  2025 235be35e-4e50-4996-80d7-ce701d2dca4b.csv.gz
-rw------- 1 root root  9850 Aug  5  2025 23a4808f-4429-41d7-adcf-c96742871613.csv.gz
-rw------- 1 root root  5263 Aug  5  2025 24166136-6ee3-4521-abaf-972fbe83d15d.csv.gz
-rw------- 1 root root  9837 Aug  5  2025 24e975f6-80e9-4489-afed-d7f93e499aeb.csv.gz
-rw------- 1 root root  6775 Aug  5  2025 29d662a9-f454-4261-8d58-f208c07cfd20.csv.gz
-rw------- 1 root root   504 Aug  5  2025 29e729f1-575c-4627-bf5a-e7bc28fdda26.csv.gz
-rw------- 1 root root  6400 Aug  5  2025 2a3ed8d1-f62c-42b5-8efe-44f6a61cd6b4.csv.gz
-rw------- 1 root root  8869 Aug  5  2025 2a8f6d94-88d4-4d72-b304-782563903dca.csv.gz
-rw------- 1 root root 11014 Aug  5  2025 2aae82c5-03f9-42dd-974d-88230a9b75f7.csv.gz
-rw------- 1 root root  7342 Aug  5  2025 2b0a7c5a-98f9-4512-a297-3ae27e805b71.csv.gz
-rw------- 1 root root  2255 Aug  5  2025 2d05ec74-7279-4b26-b3ec-d3a2e414ba43.csv.gz
-rw------- 1 root root  4210 Aug  5  2025 2db06051-769a-4daa-8e8e-3d3e6f9c5a17.csv.gz
-rw------- 1 root root  9812 Aug  5  2025 2ec7547d-bd0a-4fbf-92a8-3a4e747a53f9.csv.gz
-rw------- 1 root root  8659 Aug  5  2025 300a4242-7c38-4d7a-8911-2914ef452ab3.csv.gz
-rw------- 1 root root  9708 Aug  5  2025 30141090-2743-49fb-94e0-25bfa783bcfd.csv.gz
-rw------- 1 root root  2798 Aug  5  2025 32de9693-b5b6-4292-addd-2acbce93d8db.csv.gz
-rw------- 1 root root  8656 Aug  5  2025 333a79d3-374a-43e5-8bfe-0f14e65b3db7.csv.gz
-rw------- 1 root root  3456 Aug  5  2025 34c508d4-cbc4-46a4-8a71-890fb3d36724.csv.gz
-rw------- 1 root root  8905 Aug  5  2025 36d8aa27-272b-460f-8f2c-13d22f7150a5.csv.gz
-rw------- 1 root root  3612 Aug  5  2025 3a3fbad0-dca2-4c2b-82fb-0f6574b0bc0c.csv.gz
-rw------- 1 root root 10404 Aug  5  2025 3a442eb1-e680-40ce-afcb-e718c4f1eb09.csv.gz
-rw------- 1 root root  3943 Aug  5  2025 3a62899e-082a-4638-ab8b-b49f1ce12a20.csv.gz
-rw------- 1 root root   628 Aug  5  2025 3bdb1a29-023b-4fb5-8f49-6d285446179d.csv.gz
-rw------- 1 root root  2945 Aug  5  2025 3cc3da4a-9b07-4215-ad8c-7ef222571856.csv.gz
-rw------- 1 root root  1026 Aug  5  2025 3cd6a70c-1102-4097-b846-d42e975e901c.csv.gz
-rw------- 1 root root  7721 Aug  5  2025 3cd9d6ee-2d46-46f3-928a-109147d08549.csv.gz
-rw------- 1 root root   721 Aug  5  2025 41f2fcc5-e1a6-42d0-9b51-68682d173e6f.csv.gz
-rw------- 1 root root  5485 Aug  5  2025 425f3be7-a142-4256-af48-25ecedd8c425.csv.gz
-rw------- 1 root root  1156 Aug  5  2025 43d50656-b760-4700-8ff1-da45f17bba09.csv.gz
-rw------- 1 root root   560 Aug  5  2025 4720363c-e587-4dcf-bc00-1b3bb42e7dc8.csv.gz
-rw------- 1 root root  7781 Aug  5  2025 481aca07-ac33-4f38-98b7-3405dc3d60dc.csv.gz
-rw------- 1 root root  5897 Aug  5  2025 49a44e13-111a-4f8d-b4ea-5d3476cb83a3.csv.gz
-rw------- 1 root root  2576 Aug  5  2025 4b5a5d57-0ad9-49fc-913f-d9e33b90b159.csv.gz
-rw------- 1 root root  5583 Aug  5  2025 4b8d9e5c-1e51-4a1d-81c9-b3911f623c08.csv.gz
-rw------- 1 root root   398 Aug  5  2025 4e471779-ecbc-4b5a-b6b0-fcbfc9479faa.csv.gz
-rw------- 1 root root  9259 Aug  5  2025 4e541136-0db1-4749-b4c1-8dc03df3d4a5.csv.gz
-rw------- 1 root root  2970 Aug  5  2025 4ea2ae1d-8d6b-4c7f-ac60-27fd6e5b67b0.csv.gz
-rw------- 1 root root  9181 Aug  5  2025 4ed3225f-868e-43c6-9e57-0329d9ff9e9d.csv.gz
-rw------- 1 root root  7850 Aug  5  2025 5072f60b-88da-4fd2-8339-f2c45496ffa4.csv.gz
-rw------- 1 root root  9940 Aug  5  2025 51adda7d-b627-48e0-98be-72386fc84661.csv.gz
-rw------- 1 root root  8304 Aug  5  2025 5375b0e9-db92-4189-801a-1e9dbe1d9f61.csv.gz
-rw------- 1 root root 10591 Aug  5  2025 5bb7f10e-ea7d-4af3-adae-c0d92e8a700d.csv.gz
-rw------- 1 root root  8302 Aug  5  2025 5c7c51c5-8bd6-4997-92c1-ce4c5eda45e6.csv.gz
-rw------- 1 root root  4104 Aug  5  2025 5dc874cc-0b53-449b-bfa9-57fb665f388b.csv.gz
-rw------- 1 root root   119 Aug  5  2025 62e88542-8d2e-4148-bd5f-2a3b47cdac44.csv.gz
-rw------- 1 root root  8062 Aug  5  2025 640d48a2-510a-49e6-bb3e-5bbd92222489.csv.gz
-rw------- 1 root root  8870 Aug  5  2025 658adbe4-781c-45f9-92a7-14912fcd0701.csv.gz
-rw------- 1 root root  1201 Aug  5  2025 663de5e8-dfc8-42ad-8410-c196f6345bec.csv.gz
-rw------- 1 root root  6679 Aug  5  2025 665117c8-5dde-4655-a286-cd8ef2603d59.csv.gz
-rw------- 1 root root  8027 Aug  5  2025 674e9815-7dd1-47f9-9916-c6e53d7e1a36.csv.gz
-rw------- 1 root root 10540 Aug  5  2025 67d47ef6-5f27-43cd-912a-a40f27a43660.csv.gz
-rw------- 1 root root  8848 Aug  5  2025 6812b3d0-5a2f-4d11-960a-23fc5c4e8c7b.csv.gz
-rw------- 1 root root   253 Aug  5  2025 687c2d53-012d-4082-a5f0-edade97481a5.csv.gz
-rw------- 1 root root   132 Aug  5  2025 69c89ffd-abcc-445b-9168-d2c42ab4e7ee.csv.gz
-rw------- 1 root root  8514 Aug  5  2025 6a0fa84c-b18c-417c-b1f5-6a1a2528f7ee.csv.gz
-rw------- 1 root root  8993 Aug  5  2025 6ceb4ef3-6578-45cc-bc02-fa97614313e1.csv.gz
-rw------- 1 root root  4515 Aug  5  2025 6d10bf7a-a17c-4c87-9251-ae75e8f06f36.csv.gz
-rw------- 1 root root 10140 Aug  5  2025 6f532efb-8e13-46ca-997d-2d934b5e5a37.csv.gz
-rw------- 1 root root 11873 Aug  5  2025 6fb467a6-a780-4753-9fda-269594a5b928.csv.gz
-rw------- 1 root root   284 Aug  5  2025 7145fd25-94b9-49d3-b570-cf77f0221213.csv.gz
-rw------- 1 root root  2147 Aug  5  2025 716e0022-85e1-45f0-853a-ca8f003da51a.csv.gz
-rw------- 1 root root  2809 Aug  5  2025 71931795-5de7-4863-ae0c-3fb5edb5f9e0.csv.gz
-rw------- 1 root root  5865 Aug  5  2025 757d34ef-7f1b-41f5-b072-ea4a4f336b80.csv.gz
-rw------- 1 root root  6752 Aug  5  2025 75c633d4-6ade-471e-983a-aadc07d9383c.csv.gz
drwx------ 2 root root  4096 Apr 20 23:35 7607c6de-7244-4ba1-ab7c-5c4c4d7151ad.csv
-rw------- 1 root root  7244 Aug  5  2025 7607c6de-7244-4ba1-ab7c-5c4c4d7151ad.csv.gz
-rw------- 1 root root  9020 Aug  5  2025 77dfe9b8-5f40-49a6-ba09-706198bb8a48.csv.gz
-rw------- 1 root root   684 Aug  5  2025 787b23f7-f912-43c4-8caf-7a16c57e0256.csv.gz
-rw------- 1 root root  5794 Aug  5  2025 7b0d87b0-c099-44eb-9815-67d51d73db9a.csv.gz
-rw------- 1 root root  6294 Aug  5  2025 7b497dbd-18ec-4d3c-88dd-e9f1d67fb493.csv.gz
-rw------- 1 root root  4969 Aug  5  2025 7bb5eee8-70d6-4b16-990a-a62cf827170a.csv.gz
-rw------- 1 root root 10926 Aug  5  2025 7c34bf1b-3b8b-45cd-ae97-26f2eafe97dd.csv.gz
-rw------- 1 root root  9050 Aug  5  2025 7c885f26-7923-41a3-847e-c971eafee8d4.csv.gz
-rw------- 1 root root  3474 Aug  5  2025 7e6a98f1-73c3-4023-9bbd-acf2b70d04b5.csv.gz
-rw------- 1 root root  9104 Aug  5  2025 7e883e52-65af-4edb-9d55-a72ba5f03287.csv.gz
-rw------- 1 root root   228 Aug  5  2025 803be457-cee4-4f3f-9540-ff574c57c697.csv.gz
-rw------- 1 root root  6529 Aug  5  2025 8307ff6e-f582-49b0-81cc-39fe9966d097.csv.gz
-rw------- 1 root root  7478 Aug  5  2025 8323bb7d-6b8d-4dea-82d6-08944e6da3a9.csv.gz
-rw------- 1 root root   859 Aug  5  2025 85c88df0-b503-4329-a29f-353199f7fe5b.csv.gz
-rw------- 1 root root  9269 Aug  5  2025 883aca61-af06-4c14-ba58-8d2e4b75bfda.csv.gz
-rw------- 1 root root  5382 Aug  5  2025 885170be-d945-427d-bd3a-b0524ddc3105.csv.gz
-rw------- 1 root root  1955 Aug  5  2025 89ff7373-ee85-4764-a4dd-90138af9af85.csv.gz
-rw------- 1 root root  8045 Aug  5  2025 8a01ec4c-6222-4efd-9beb-0adb12e00a2b.csv.gz
-rw------- 1 root root   880 Aug  5  2025 8a2a2baf-826f-445d-a7fe-3a9b7f5d2334.csv.gz
-rw------- 1 root root  9512 Aug  5  2025 8b13d979-315f-4357-8f0e-7c12df0a6ca8.csv.gz
-rw------- 1 root root  2859 Aug  5  2025 8c09fe40-2c9e-49a1-afc9-a37138658d3b.csv.gz
-rw------- 1 root root  7572 Aug  5  2025 8c0d11a7-1838-4db4-9319-5d171522655d.csv.gz
-rw------- 1 root root    51 Aug  5  2025 8f1c82eb-5e71-4187-a0a3-f2b58d8d99bd.csv.gz
-rw------- 1 root root  2025 Aug  5  2025 900bd2b1-a14f-4775-8f78-07ba77caf23b.csv.gz
-rw------- 1 root root    51 Aug  5  2025 91297102-4775-4ea1-a10d-4530e3c2f0af.csv.gz
-rw------- 1 root root   588 Aug  5  2025 9276d1e3-6954-460f-bd75-7f99fa01345c.csv.gz
-rw------- 1 root root  6669 Aug  5  2025 9519432e-bf05-4f6c-80d7-f61e930f14ba.csv.gz
-rw------- 1 root root  6912 Aug  5  2025 9548d1c4-bd4a-4841-9146-c0678135069d.csv.gz
-rw------- 1 root root 10964 Aug  5  2025 95f9f3a8-128c-4382-aa4b-6ea319b497ae.csv.gz
-rw------- 1 root root  5552 Aug  5  2025 967b5d47-3ff4-4364-b2e8-b2243c490d7d.csv.gz
-rw------- 1 root root 11376 Aug  5  2025 96a272fc-166f-4fe4-8aeb-3874264f3b54.csv.gz
-rw------- 1 root root  7995 Aug  5  2025 997c6352-6724-4985-b48c-9c3f08437964.csv.gz
-rw------- 1 root root  6046 Aug  5  2025 9b4822a9-8506-4026-8f8f-803410f95a52.csv.gz
-rw------- 1 root root 11043 Aug  5  2025 9c4b0b2a-92e1-4aeb-be90-98f65c1d4217.csv.gz
-rw------- 1 root root  7037 Aug  5  2025 9f956795-08fb-4518-98c5-481696722acd.csv.gz
-rw------- 1 root root  9310 Aug  5  2025 a0746eca-480e-41ac-bc92-d31568b2bdaf.csv.gz
-rw------- 1 root root  7458 Aug  5  2025 a09f7021-3875-48f3-ab98-b7ae623fb91a.csv.gz
-rw------- 1 root root  1318 Aug  5  2025 a0fce948-41d2-4070-bad2-ab8d17bf97d8.csv.gz
-rw------- 1 root root  8741 Aug  5  2025 a1395d16-e27d-4ff3-80ba-2bb22049c19d.csv.gz
-rw------- 1 root root  5179 Aug  5  2025 a1623554-43d6-4038-b28a-bd74a96b9c97.csv.gz
-rw------- 1 root root  6485 Aug  5  2025 a255dc52-384b-4d4c-a612-33a02fa6c409.csv.gz
-rw------- 1 root root  1754 Aug  5  2025 a2664330-dcfa-4d43-a788-8904343b6a00.csv.gz
-rw------- 1 root root  7866 Aug  5  2025 a4b481fd-66b2-4b01-a3a7-906af1f81663.csv.gz
-rw------- 1 root root 10699 Aug  5  2025 a575b34b-0787-4762-a06a-5604de6d005b.csv.gz
-rw------- 1 root root  6782 Aug  5  2025 a60ebd9e-fa87-4722-8960-b26290ddae1a.csv.gz
-rw------- 1 root root  8710 Aug  5  2025 a70d820b-e850-44c4-ab12-1b40e0f7ae39.csv.gz
-rw------- 1 root root  5540 Aug  5  2025 a7633bbc-3145-4bba-b86b-cef5e4ae3273.csv.gz
-rw------- 1 root root  9927 Aug  5  2025 a7db3311-aa07-4580-b552-73c18657c803.csv.gz
-rw------- 1 root root  1234 Aug  5  2025 a81eedd1-fb39-4763-bf76-a0472f78ce9f.csv.gz
-rw------- 1 root root  2245 Aug  5  2025 a8800ef0-619c-4a3c-af5b-df1d2a3a6f71.csv.gz
-rw------- 1 root root  8173 Aug  5  2025 a9dfbe4d-4076-48c7-a72b-342fe4c12514.csv.gz
-rw------- 1 root root  7806 Aug  5  2025 aa8d1b7a-14c6-4490-a57b-d3893ac28b03.csv.gz
-rw------- 1 root root  1834 Aug  5  2025 aae509f5-ab41-43a0-85c2-5dfad0ed520a.csv.gz
-rw------- 1 root root  9958 Aug  5  2025 ab23fe51-7249-4c81-bec3-451b6ab1d140.csv.gz
-rw------- 1 root root    51 Aug  5  2025 adc70680-fedc-481e-be34-32c6630ab3cd.csv.gz
-rw------- 1 root root  5993 Aug  5  2025 aea11c01-40d9-479e-aa27-0b8bf464de52.csv.gz
-rw------- 1 root root  4473 Aug  5  2025 aef21a29-6b16-4d49-9a07-96c12fcd5698.csv.gz
-rw------- 1 root root  6277 Aug  5  2025 b24987c0-4530-45b4-8dc1-c42c4e0cd7ad.csv.gz
-rw------- 1 root root  2693 Aug  5  2025 b318de0d-0b0a-4ba8-a7be-9fcf7b9d8c67.csv.gz
-rw------- 1 root root  7956 Aug  5  2025 b31b6e69-0384-4d5d-8eac-5f512862690b.csv.gz
-rw------- 1 root root   930 Aug  5  2025 ba240e43-900d-4477-8718-b9487ed24d7d.csv.gz
-rw------- 1 root root  2191 Aug  5  2025 bdb64352-b982-4aab-8d98-3c56c5a6441f.csv.gz
-rw------- 1 root root   158 Aug  5  2025 be0e8360-24c6-4d74-ab72-aadf8d8acc82.csv.gz
-rw------- 1 root root  8341 Aug  5  2025 be2b627b-a267-4bd6-a36b-c9dcc2065f0c.csv.gz
-rw------- 1 root root  7890 Aug  5  2025 c131a94c-b958-454b-bbd0-2f0de3b7ae5a.csv.gz
-rw------- 1 root root  3046 Aug  5  2025 c29d3319-8920-46b9-9b3a-11c36630c87d.csv.gz
-rw------- 1 root root  5006 Aug  5  2025 c35d219d-59d9-4197-b981-ea0aa6506e79.csv.gz
-rw------- 1 root root  9128 Aug  5  2025 c7492565-48cd-4b52-af25-3aee61a391ad.csv.gz
-rw------- 1 root root  7763 Aug  5  2025 c7acafcf-f5dd-411e-b90c-988279852fb8.csv.gz
-rw------- 1 root root  9833 Aug  5  2025 c7c4392b-02ee-40f4-a22f-ab2386c6ccf5.csv.gz
-rw------- 1 root root  7185 Aug  5  2025 c9fd26bd-1c5d-4d80-a298-8304267cfb4c.csv.gz
-rw------- 1 root root  8197 Aug  5  2025 ca202c8f-5071-4358-8851-3c580ec157b1.csv.gz
-rw------- 1 root root  3809 Aug  5  2025 cc25830a-254a-487f-acec-c0afb3962679.csv.gz
-rw------- 1 root root  7804 Aug  5  2025 cc6aaebf-0430-4bf2-b3b7-f416daf008c7.csv.gz
-rw------- 1 root root  5070 Aug  5  2025 cdcb783e-c9fd-4eab-9d6c-2a53e4082a1f.csv.gz
-rw------- 1 root root  7878 Aug  5  2025 cffbcf00-a329-4d57-a622-6e85ca913704.csv.gz
-rw------- 1 root root  8086 Aug  5  2025 d046a3ef-1402-4530-855c-481798c41ccd.csv.gz
-rw------- 1 root root  2536 Aug  5  2025 d127b095-98d4-4149-bdfc-c9f9739e6f18.csv.gz
-rw------- 1 root root  2156 Aug  5  2025 d28b2c23-1da4-4b64-be94-df4aa6121559.csv.gz
-rw------- 1 root root  9342 Aug  5  2025 d62a5591-4c0c-4c95-9187-faa64b95f9fc.csv.gz
-rw------- 1 root root  8944 Aug  5  2025 dafdc3d9-e474-4556-8958-204f68ad5ebc.csv.gz
-rw------- 1 root root  1536 Aug  5  2025 db082772-c8cc-4df4-a647-6a80ee2db9ce.csv.gz
-rw------- 1 root root  1439 Aug  5  2025 db2bffd9-c5b5-4fed-9d55-09a087ce0e6e.csv.gz
-rw------- 1 root root   615 Aug  5  2025 dc65ee54-ad64-4cce-8d0a-878033ff02d7.csv.gz
-rw------- 1 root root 11782 Aug  5  2025 dcc3e9ff-9c05-4e17-9798-fd5114be77a9.csv.gz
-rw------- 1 root root  8570 Aug  5  2025 deb03e25-16f1-403a-8152-891f50b50ae4.csv.gz
-rw------- 1 root root  6954 Aug  5  2025 df3a6b7a-7e27-4003-beea-2cb5cf08da83.csv.gz
-rw------- 1 root root  8196 Apr 20 21:10 .DS_Store
-rw------- 1 root root  8710 Aug  5  2025 e027002a-cf96-4132-a4ac-2003e945258d.csv.gz
-rw------- 1 root root  9807 Aug  5  2025 e05bec91-93e2-4b23-9d4f-ae79dade8451.csv.gz
-rw------- 1 root root  1768 Aug  5  2025 e31e0dfd-b00c-43e4-a1ea-f5110bf01c1c.csv.gz
-rw------- 1 root root   380 Aug  5  2025 e3e5e4aa-5950-4f1f-915c-c67598965b03.csv.gz
-rw------- 1 root root 10182 Aug  5  2025 e5be76f8-6461-481b-834e-b44f8f880273.csv.gz
-rw------- 1 root root  9627 Aug  5  2025 e6081755-d7f3-4c26-ab40-0709b8ad41ef.csv.gz
-rw------- 1 root root  7529 Aug  5  2025 e8606fff-0ac6-4832-bb79-323b89ebcf2e.csv.gz
-rw------- 1 root root  8311 Aug  5  2025 e89b1ea7-a2ea-4f2f-ae5a-9a9d29af8639.csv.gz
-rw------- 1 root root  9129 Aug  5  2025 e8c7086f-007a-41c5-a7dc-af81612ab14d.csv.gz
-rw------- 1 root root  6829 Aug  5  2025 eb4e1be4-29de-4120-9727-0ce8041da479.csv.gz
-rw------- 1 root root   359 Aug  5  2025 edec36ec-64c2-4cf8-af5c-99f4c8972d30.csv.gz
-rw------- 1 root root  4666 Aug  5  2025 edf9689d-5d97-4fe9-b3e7-64c96d9a169c.csv.gz
-rw------- 1 root root  1507 Aug  5  2025 efc0dabd-1c17-4a63-89ca-21f65250e43f.csv.gz
-rw------- 1 root root  9320 Aug  5  2025 f0bf3cda-f934-459f-a731-dd7eda243ae7.csv.gz
-rw------- 1 root root  2614 Aug  5  2025 f2e8ab49-ce1b-45f4-9632-cf596f1196bb.csv.gz
-rw------- 1 root root   544 Aug  5  2025 f30085f9-fdb0-49fb-b242-2ad8286b242c.csv.gz
-rw------- 1 root root  6949 Aug  5  2025 f3a1263e-f498-4942-829a-f40d186caa08.csv.gz
-rw------- 1 root root  4075 Aug  5  2025 f596b3ca-7b25-4632-b986-7b44448d3f2f.csv.gz
-rw------- 1 root root  7577 Aug  5  2025 f5c8d104-4839-4aca-b2f5-8c2fc4b98af9.csv.gz
-rw------- 1 root root  9505 Aug  5  2025 f610ffea-f6cb-4182-bbe7-19ff8fbe66ee.csv.gz
-rw------- 1 root root  7064 Aug  5  2025 f732e878-e538-49b8-97d3-49ca29e9a3f8.csv.gz
-rw------- 1 root root  9510 Aug  5  2025 f9264a9d-99d8-4937-8bda-eb620c0c1ed7.csv.gz
-rw------- 1 root root  8043 Aug  5  2025 f983485d-f954-4693-9c2c-981710c06dd0.csv.gz
-rw------- 1 root root  7222 Aug  5  2025 fabef151-53c8-4a46-9897-0180868a53f5.csv.gz
-rw------- 1 root root  7148 Aug  5  2025 fae38580-1e2d-4491-9de5-7b75703ba4ce.csv.gz
-rw------- 1 root root   554 Aug  5  2025 fb3a4dd7-3cb5-438e-a75d-244d1aec4790.csv.gz
-rw------- 1 root root  9290 Aug  5  2025 fcb14a4c-1ffa-4315-872a-a38833459885.csv.gz
-rw------- 1 root root  5724 Aug  5  2025 fd79ab30-1199-4619-adbd-577d715d86ce.csv.gz
-rw------- 1 root root 11046 Aug  5  2025 fdbd8c07-720c-4ae5-a3d8-aad56b54688c.csv.gz
-rw------- 1 root root   384 Aug  5  2025 README.md

## Prepocess Steps

In [ ]:
from pre_processing.fitbit_preprocessing import prepare_fitbit_training_data

dataset = prepare_fitbit_training_data(
    sleep_path="/path/to/sleep-data/<id>.csv.gz",
    heart_path="/path/to/heart-rate/<id>.csv.gz",
    window_sec=60,
    epoch_sec=30,
    sampling_hz=1.0,
    centered=True,
)

X, y = dataset.X, dataset.y
print(X.shape, y.shape)

## Reading the sleep Data

In [2]:
# Then read from it
import pandas as pd
df_sleep = pd.read_csv("drive/MyDrive/fitbit/sleep-data/02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz", compression='gzip')
display(df_sleep.head(30))

    sleepId                 dateTime     level  seconds
0         1  2018-04-08T22:22:30.000    asleep     4980
1         1  2018-04-08T23:45:30.000  restless       60
2         1  2018-04-08T23:46:30.000    asleep     2040
3         1  2018-04-09T00:20:30.000  restless      120
4         1  2018-04-09T00:22:30.000    asleep      120
5         1  2018-04-09T00:24:30.000  restless       60
6         1  2018-04-09T00:25:30.000    asleep      480
7         1  2018-04-09T00:33:30.000  restless       60
8         1  2018-04-09T00:34:30.000    asleep      120
9         1  2018-04-09T00:36:30.000  restless      120
10        1  2018-04-09T00:38:30.000    asleep     1980
11        1  2018-04-09T01:11:30.000  restless       60
12        1  2018-04-09T01:12:30.000    asleep      240
13        1  2018-04-09T01:16:30.000  restless       60
14        1  2018-04-09T01:17:30.000    asleep      300
15        1  2018-04-09T01:22:30.000  restless      180
16        1  2018-04-09T01:25:30.000    asleep      420
17        1  2018-04-09T01:32:30.000  restless      120
18        1  2018-04-09T01:34:30.000    asleep      420
19        1  2018-04-09T01:41:30.000  restless       60
20        1  2018-04-09T01:42:30.000    asleep       60
21        1  2018-04-09T01:43:30.000  restless       60
22        1  2018-04-09T01:44:30.000    asleep      480
23        1  2018-04-09T01:52:30.000  restless       60
24        1  2018-04-09T01:53:30.000    asleep       60
25        1  2018-04-09T01:54:30.000  restless      120
26        1  2018-04-09T01:56:30.000    asleep      360
27        1  2018-04-09T02:02:30.000  restless      120
28        1  2018-04-09T02:04:30.000    asleep      120
29        1  2018-04-09T02:06:30.000  restless      120

In [4]:
# Then read from it
import pandas as pd
df_heart = pd.read_csv("drive/MyDrive/fitbit/heart-rate/02581754-36cd-4b23-85ea-bf995c6dec83.csv.gz", compression='gzip')
display(df_heart.head(30))

                  Timestamp  HeartRatePPG
0   2018-04-09T00:00:02.000          62.0
1   2018-04-09T00:00:07.000          62.0
2   2018-04-09T00:00:12.000          61.0
3   2018-04-09T00:00:22.000          62.0
4   2018-04-09T00:00:37.000          62.0
5   2018-04-09T00:00:42.000          63.0
6   2018-04-09T00:00:47.000          64.0
7   2018-04-09T00:00:52.000          62.0
8   2018-04-09T00:00:57.000          61.0
9   2018-04-09T00:01:02.000          60.0
10  2018-04-09T00:01:07.000          62.0
11  2018-04-09T00:01:12.000          63.0
12  2018-04-09T00:01:27.000          59.0
13  2018-04-09T00:01:32.000          60.0
14  2018-04-09T00:01:37.000          61.0
15  2018-04-09T00:01:42.000          62.0
16  2018-04-09T00:01:57.000          62.0
17  2018-04-09T00:02:02.000          61.0
18  2018-04-09T00:02:07.000          60.0
19  2018-04-09T00:02:12.000          61.0
20  2018-04-09T00:02:27.000          61.0
21  2018-04-09T00:02:32.000          60.0
22  2018-04-09T00:02:37.000          62.0
23  2018-04-09T00:02:47.000          61.0
24  2018-04-09T00:02:57.000          62.0
25  2018-04-09T00:03:02.000          61.0
26  2018-04-09T00:03:09.000          61.0
27  2018-04-09T00:03:14.000          62.0
28  2018-04-09T00:03:19.000          61.0
29  2018-04-09T00:03:29.000          62.0